#!/bin/sh

# PROVIDE: tun2socks
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="tun2socks"
rcvar="tun2socks_enable"

load_rc_config $name

: ${tun2socks_enable:=no}

tun2socks_command="/usr/local/bin/hev-socks5-tunnel"
tun2socks_config="/usr/local/etc/singbox/hev-socks5-tunnel.yml"

pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -f ${tun2socks_command} ${tun2socks_config}"

run_rc_command "$1"